"use client";
import { FormEvent, useEffect, useState } from "react";
import { wedding } from "@/config/wedding";
import { songRequests, SongRequest } from "@/services/songRequests";
import { rsvps } from "@/services/rsvps";
import { MusicPlayer } from "@/components/MusicPlayer";
import { SectionBlend } from "@/components/SectionBlend";
import { ScrollProgress } from "@/components/ScrollProgress";
import { AmbientGlow } from "@/components/AmbientGlow";
import { ParallaxImage } from "@/components/ParallaxImage";
import { WeddingNav } from "@/components/WeddingNav";
import { GiftSection } from "@/components/GiftSection";

const photos=["https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1600&q=85","https://images.unsplash.com/photo-1606800052052-a08af7148866?auto=format&fit=crop&w=1200&q=85","https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1200&q=85","https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1200&q=85"];
function useCountdown(){const [left,setLeft]=useState({d:0,h:0,m:0,s:0});useEffect(()=>{const tick=()=>{const ms=Math.max(0,new Date("2026-11-22T00:00:00Z").getTime()-Date.now());setLeft({d:Math.floor(ms/864e5),h:Math.floor(ms/36e5)%24,m:Math.floor(ms/6e4)%60,s:Math.floor(ms/1e3)%60})};tick();const x=setInterval(tick,1000);return()=>clearInterval(x)},[]);return left}
function Reveal({children,className=""}:{children:React.ReactNode;className?:string}){return <div className={`reveal ${className}`}>{children}</div>}
export default function Home(){const time=useCountdown();const [songs,setSongs]=useState<SongRequest[]>(()=>songRequests.all());const [songNote,setSongNote]=useState("");const [rsvpNote,setRsvpNote]=useState("");const sendSong=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);songRequests.add({guestName:String(f.get("guestName")),artist:String(f.get("artist")),title:String(f.get("title")),link:String(f.get("link"))||undefined});setSongs(songRequests.all());setSongNote("✓  Listo. Ya tiene trabajo el DJ.");e.currentTarget.reset()};const sendRsvp=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);rsvps.add({fullName:String(f.get("name")),attending:String(f.get("attending")) as "yes"|"no",guestCount:Number(f.get("guests")),dietary:String(f.get("dietary")),message:String(f.get("message"))});setRsvpNote("Gracias por acompañarnos. ¡Nos hace muy felices!");e.currentTarget.reset()};return <main><ScrollProgress/><WeddingNav/>
<section id="inicio" className="hero" style={{backgroundImage:`linear-gradient(180deg,rgba(17,16,15,.2),rgba(17,16,15,.76)),url(${photos[0]})`}}><video autoPlay muted loop playsInline poster={wedding.assets.heroFallback} src={wedding.assets.heroVideo}/><div className="hero-copy"><p className="eyebrow">21 NOV 2026</p><h1>KARINA <em>&</em> MARCELO</h1><p className="eyebrow">NOS CASAMOS</p><blockquote>“Y queremos que formes parte de nuestra historia.”</blockquote></div><span className="scroll">SCROLL <b>↓</b></span></section>
<section className="intro snap-scene"><div className="sticky-words"><p><small>SÍ,</small><br/>HAY BODA.</p><p>HAY JODA.</p><p>Y QUEREMOS<br/>QUE SEAS PARTE.</p></div></section>
<section id="nosotros" className="couple snap-scene"><SectionBlend tone="warmGlow"/><AmbientGlow className="glow-couple"/><ParallaxImage className="couple-main" src={photos[1]} alt="Pareja celebrando"/><ParallaxImage className="couple-small" src={photos[2]} alt="Detalles de una boda"/><Reveal className="couple-copy"><p className="eyebrow">UNA HISTORIA</p><h2>Karina<br/><em>&</em> Marcelo</h2><p>“Una historia que sigue escribiéndose.”</p></Reveal></section>
<section className="story" style={{backgroundImage:`linear-gradient(0deg,rgba(17,16,15,.86),rgba(17,16,15,.25)),url(${photos[3]})`}}><div className="story-sticky"><p>Nos encontramos.</p><p>Nos elegimos.</p><p>Nos acompañamos.</p><p>Y ahora...</p><strong>NOS CASAMOS.</strong></div></section>
<section className="countdown snap-scene"><SectionBlend tone="imageDissolve"/><AmbientGlow className="glow-countdown"/><p className="eyebrow">FALTA MUY POQUITO...</p><div className="count-grid">{[[time.d,"DÍAS"],[time.h,"HORAS"],[time.m,"MINUTOS"],[time.s,"SEGUNDOS"]].map(([n,l])=><div key={String(l)}><b>{String(n).padStart(2,"0")}</b><span>{l}</span></div>)}</div></section>
<section id="evento" className="event"><img src={photos[0]} alt="Atardecer de casamiento"/><div><p className="eyebrow">EL GRAN DÍA</p><h2>SÁBADO<br/><b>21</b><br/>NOVIEMBRE<br/>2026</h2><p className="event-time">21:00 HS</p><h3>{wedding.venue.name}</h3><p>{wedding.venue.address}</p><a href={wedding.venue.mapUrl} target="_blank">CÓMO LLEGAR →</a></div></section>
<section id="cronograma" className="timeline"><p className="eyebrow">CRONOGRAMA</p><h2>UNA NOCHE<br/>PARA RECORDAR</h2><ol>{wedding.schedule.map(([at,name])=><Reveal key={at}><li><time>{at}</time><span>{name}</span></li></Reveal>)}</ol></section>
<section id="dress-code" className="dress snap-scene"><AmbientGlow className="glow-dress"/><div><p className="eyebrow">DRESS</p><h2>DRESS<br/><em>CODE</em><br/>FORMAL</h2><p>“Elegantes, cómodos y listos para bailar.”</p></div><div className="dress-imgs"><small>01 · ELLA</small><ParallaxImage src={photos[2]} alt="Look formal"/><small>02 · ÉL</small><ParallaxImage src={photos[1]} alt="Look formal femenino"/></div></section>
<section id="musica" className="songs"><AmbientGlow className="glow-songs"/><div className="vinyl" aria-hidden="true"><i/></div><p className="eyebrow">TU TEMA PARA LA FIESTA</p><h2>QUE SUENE<br/><em>TU TEMA</em></h2><p>Una buena fiesta también la hacen los invitados.<br/>Dejanos esa canción que no puede faltar.</p><div className="wave">∿ ∿ ∿ ∿ ∿ ∿ ∿ ∿</div><form onSubmit={sendSong}><input required name="guestName" placeholder="Nombre"/><input required name="artist" placeholder="Artista"/><input required name="title" placeholder="Canción"/><input name="link" type="url" placeholder="Link Spotify / YouTube (opcional)"/><button>SUMAR A LA PLAYLIST →</button></form>{songNote&&<p className="form-note">{songNote}</p>}{songs.length>0&&<div className="requested"><p className="eyebrow">ALGUNOS TEMAS QUE YA PIDIERON</p>{songs.slice(0,5).map(s=><p key={s.id}><b>{s.title}</b> — {s.artist} <small>· {s.guestName}</small></p>)}</div>}</section><GiftSection/>
<section id="galeria" className="gallery"><p className="eyebrow">GALERÍA</p><h2>NUESTROS<br/>MOMENTOS</h2><div className="masonry">{photos.concat(photos.slice(1,3)).map((src,i)=><img key={i} src={src} alt="Momento de Karina y Marcelo"/>)}</div></section>
<section id="rsvp" className="rsvp"><p className="eyebrow">RSVP</p><h2>¿NOS<br/><em>ACOMPAÑÁS?</em></h2><form onSubmit={sendRsvp}><input required name="name" placeholder="Nombre y apellido"/><fieldset><legend>¿Vas a asistir?</legend><label><input required type="radio" name="attending" value="yes"/> Sí, obvio</label><label><input required type="radio" name="attending" value="no"/> No voy a poder</label></fieldset><input required min="1" name="guests" type="number" placeholder="Cantidad de personas"/><input name="dietary" placeholder="Restricciones alimentarias"/><textarea name="message" placeholder="Mensaje para los novios"/><button>CONFIRMAR ASISTENCIA →</button></form>{rsvpNote&&<p className="form-note">{rsvpNote}</p>}</section>
<section className="forever" style={{backgroundImage:`linear-gradient(0deg,rgba(17,16,15,.78),rgba(17,16,15,.22)),url(${photos[0]})`}}><div><p>Hay días especiales.</p><p>Hay personas especiales.</p><p>Y hay momentos<br/>que queremos guardar</p><h2>PARA<br/>SIEMPRE.</h2></div></section>
<footer style={{backgroundImage:`linear-gradient(0deg,rgba(17,16,15,.82),rgba(17,16,15,.45)),url(${photos[3]})`}}><p className="monogram">K & M</p><p>21 · 11 · 2026</p><p>Nos vemos para celebrar.</p><h2>KARINA<br/><em>&</em><br/>MARCELO</h2></footer><MusicPlayer/></main>}
