export const wedding = {
  slug: "karina-marcelo-2026",
  couple: {
    bride: "Karina",
    groom: "Marcelo",
    initials: "K & M",
    displayName: "Karina & Marcelo",
  },
  date: {
    iso: "2026-11-21",
    startAt: "2026-11-21T21:00:00-03:00",
    time: "21:00",
    weekday: "SÁBADO",
    day: "21",
    month: "NOVIEMBRE",
    year: "2026",
    hero: "21 NOV 2026",
    display: "21 · 11 · 2026",
    compact: "21.11.2026",
    report: "21 - 11 - 2026",
  },
  venue: {
    name: null as string | null,
    address: "Luzuriaga 4328",
    mapUrl: "https://www.google.com/maps?q=-27.385156631469727,-55.933624267578125&z=17&hl=es",
  },
  dressCode: {
    title: "ELEGANTE SPORT",
    description: "Ponete lindo, cómodo y vení listo para bailar.",
    outdoor: "El festejo es al aire libre.",
    footwear: "Te recomendamos usar calzado apto para el pasto.",
  },
  gift: {
    enabled: true,
    accountHolder: null as string | null,
    bankName: null as string | null,
    alias: "MARCE.DIJO.SI",
    cbu: "2850001040094592235498",
    accountType: null as string | null,
    currency: "ARS",
    qrImage: null as string | null,
  },
  schedule: [
    ["21:00", "Llegada"],
    ["21:30", "Ceremonia"],
    ["22:00", "Brindis"],
    ["23:00", "Cena"],
    ["23:30", "Fiesta"],
    ["05:00", "Volvemos... o eso intentaremos."],
  ],
  copy: {
    metadataTitle: "Karina & Marcelo | 21.11.2026",
    metadataDescription: "Nos casamos. Te esperamos para compartir una noche inolvidable.",
    heroQuote: "Y queremos que formes parte de nuestra historia.",
    transition: ["Y QUEREMOS", "QUE SEAS PARTE."],
    storyQuote: "Una historia que sigue escribiéndose.",
    closing: "Nos vemos para celebrar.",
    credit: "Desarrollado por Impulso Digital Misiones · 2026",
  },
  metadata: {
    siteUrl: "https://marcelo-y-karina.impulsodigitalmisiones.com.ar",
    siteName: "Karina & Marcelo",
    ogImage: "/og/karina-marcelo-share.jpg",
    ogAlt: "Karina y Marcelo — 21 de noviembre de 2026",
  },
  assets: {
    heroVideo: null as string | null,
    heroFallback: "/images/karina-marcelo/photo-05.webp",
    audio: "/audio/karina-marcelo/wedding-theme.mp3",
    photos: [
      { src: "/images/karina-marcelo/photo-01.webp", alt: "Karina y Marcelo en distintos momentos compartidos", position: "50% 50%" },
      { src: "/images/karina-marcelo/photo-02.webp", alt: "Karina y Marcelo contemplando la ciudad junto al mar", position: "50% 58%" },
      { src: "/images/karina-marcelo/photo-03.webp", alt: "Karina y Marcelo frente al barco durante su viaje", position: "50% 54%" },
      { src: "/images/karina-marcelo/photo-04.webp", alt: "Karina y Marcelo caminando juntos por la playa", position: "50% 48%" },
      { src: "/images/karina-marcelo/photo-05.webp", alt: "Karina y Marcelo abrazados mirando las luces de la ciudad", position: "50% 56%" },
    ],
  },
  brand: {
    name: "Impulso Digital Misiones",
    whatsappUrl: "https://api.whatsapp.com/send/?phone=5491137942442&text=Hola!%20me%20gust%C3%B3%20la%20invitaci%C3%B3n%20digital%20de%20Marcelo%20y%20Karina%20y%20quer%C3%ADa%20consultar%20al%20respecto.&type=phone_number&app_absent=0",
    whatsappLabel: "Consultas por WhatsApp",
  },
} as const;
